### ISSUE TITLE
programming language

### ISSUE THREAD

**Issue by Pantyhose-X** [jordan4ibanez/Crafter-Java#6]
Should the Crafter project use a programming language that is faster, smaller, and consumes less resources?
[Odin](https://github.com/odin-lang/Odin), [Nelua](https://github.com/edubart/nelua-lang) ,[Nim](https://github.com/nim-lang/Nim) , [V](https://github.com/vlang/v) , [Carbon](https://github.com/carbon-language/carbon-lang), [Crystal](https://github.com/crystal-lang/crystal), [Rust](https://github.com/rust-lang/rust) ,  [Zig](https://github.com/ziglang/zig) , [Julia](https://github.com/JuliaLang/julia) ,[Go](https://go.dev/), [D](https://dlang.org/)

**Comment by jordan4ibanez** [comment]
Kotlin
